services:
  postgres:
    image: postgres:17-alpine
    container_name: hotel_booking_postgres
    environment:
      POSTGRES_DB: hotel_booking_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
