# Generated by Django 5.2.16 on 2026-07-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hotelroom',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='hotels_book_room_id_b403dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='hotelroom',
            name='hotels_hote_price_p_9023f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='hotelroom',
            name='hotels_hote_created_f57c6e_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelroom'),
        ),
    ]
